name: Continuous Integration

on: [push]

jobs:
  # Uses: https://github.com/haskell/actions/tree/main/setup
  test:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.7'
          cabal-version: '3.12.1.0' # Exact version of Cabal

      - name: Clean
        run: make clean

      # Reference: https://github.com/actions/cache/blob/main/examples.md#haskell---stack
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          # key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          key: ${{ runner.os }}-stack-global-haskell-notes
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          # key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          key: ${{ runner.os }}-stack-work-haskell-notes
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - name: Compile
        run: make debug && make compile

      - name: Document
        run: make debug && make document-scripts

      - name: Test
        run: make debug && make test
