name: Continuous Integration

on: [push]

jobs:
  # Uses: https://github.com/haskell/actions/tree/main/setup
  test:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.7'
          cabal-version: '3.8' # Exact version of Cabal

      - name: Clean
        run: make clean

      - name: Compile
        run: make debug && make compile

      - name: Document
        run: make debug && make document-scripts

      - name: Test
        run: make debug && make test
